[tool.poetry]
name = "ReCAP-Utils"
version = "0.1.1"
description = ""
authors = ["Mirko Lenz <info@mirko-lenz.de>"]

[tool.poetry.scripts]
recap-utils = "recap_utils.app:cli"

[tool.poetry.dependencies]
python = "^3.7"
recap-argument-graph = "^0.1.0"
click = "^7.0"
tomlkit = "^0.5.8"
recap-argument-graph-translator = "^0.1.1"
click-pathlib = "^2019.12.28"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
mypy = "^0.761"
pylint = "^2.4.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
